[package]
name = "juju-os"
version = "0.1.0"
authors = ["Julien Levesy <jlevesy@gmail.com>"]
edition = "2018"

[dependencies]
bootloader = "0.8.0"
volatile = "0.2.6"
spin = "0.5.2"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

